"use client"

import getAllUser from "@/lib/getAllUser";
import Link from "next/link";
import { useRouter } from "next/navigation";

// export const metadata = {
//   title: "user Page",
//   description: "Generated by create next app",
// };

export default async function UserPage({params}) {
  const userData = getAllUser();
  const router = useRouter();
  console.log("This is router", router);
  console.log("This is params", params);
  const user = await userData;
  return (
    <section>
      <h1>USERS---dymnamic page</h1>
      <ul>
        {user.map((val, ind) => (
          <li key={`${val.id}`}>
            <Link href={`users/${val.id}`}>{val.name}</Link>
          </li>
        ))}
      </ul>
    </section>
  );
}
